flags: {}
extra-package-dbs: []
packages:
- '.'
- location: /home/j/dev/apps/haskell/libraries/12-text-generic-pretty
  extra-dep: true
- location: /home/j/dev/apps/haskell/libraries/50-betfair-api
  extra-dep: true
extra-deps:
- text-generic-pretty-1.2.7
- time-units-1.0.0
resolver: lts-8.15
